name: Manual Deploy to New Account Repository

on:
  workflow_dispatch: # Allows manual triggering via GitHub Actions UI
    inputs:
      branch:
        description: 'Branch to deploy (main or gh-pages)'
        required: true
        default: 'main'

jobs:
  deploy_to_main:
    if: ${{ github.event.inputs.branch == 'main' }}
    name: Push Changes to Main Branch in New Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to Main Branch in New Repository
        env:
          TOKEN: ${ secrets.PROD_ACCESS_TOKEN }
        run: |
          git remote add production https://github.com/alexWandugu/alexWandugu.github.io.git
          git push https://${TOKEN}@github.com/alexWandugu/alexWandugu.github.io.git main:main

  deploy_to_gh_pages:
    if: ${{ github.event.inputs.branch == 'gh-pages' }}
    name: Deploy Dist Folder to gh-pages Branch in New Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Dist Folder to gh-pages
        env:
          TOKEN: ${ secrets.PROD_ACCESS_TOKEN }
        run: |
          git remote add production https://${TOKEN}@github.com/alexWandugu/alexWandugu.github.io.git
          git fetch production
          git switch --orphan gh-pages
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Deploy to gh-pages"
          git push --force production gh-pages
